PersonalProject/Models/ErrorViewModel.cs
namespace PersonalProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PersonalProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalProject.Models;
using System.Diagnostics;

namespace PersonalProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PersonalProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalProject.BLL.Models;
using PersonalProject.BLL.Services.Interfaces;

namespace PersonalProject.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddEditProduct(int? id)
        {
            var productViewModel = _productService.GetProductById(id);

            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult AddEditProduct(ProductModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var result = false;
            if (model != null && model.Id != 0)
                result = _productService.UpdateProduct(model);
            else
                result = _productService.AddProduct(model);

            return result ? RedirectToAction("GetAllProducts") : UnprocessableEntity(result);
        }

        public IActionResult GetAllProducts()
        {
            var products = _productService.GetAllProducts();
            return View(products);
        }

        public IActionResult DeleteProduct(int id)
        {
            _productService.DeleteProduct(id);
            return RedirectToAction("GetAllProducts");
        }

        public IActionResult DisplayProductsToSell()
        {
            var model = _productService.GetAllProductsToSell();

            return View("ProductsToSell", model);
        }

        [HttpPost]
        public ActionResult AddProductsToShoppingCart(ProductToSellModel product)
        {
            var model = _productService.AddProductsToSellToShoppingCart(product);
            return Json(new { success = model.ShoppingCartProducts.Any() });
        }

        [HttpPost]
        public JsonResult DeleteProductFromShoppingCart(int productId)
        {
            var result = _productService.DeleteProductFromShoppingCart(productId);
            return Json(new { success = result });
        }

        [HttpPost]
        public JsonResult SaveOrder()
        {
            var result = _productService.SaveOrder();
            return Json(new { success = result });
        }

        [HttpGet]
        public ActionResult GetAllOrders()
        {
            var orders = _productService.GetAllOrders();
            return View("Orders", orders);
        }
    }
}

PersonalProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PersonalProject/Views/Product/AddEditProduct.cshtml
@model PersonalProject.BLL.Models.ProductModel

@{
    ViewBag.Title = Model.Id != 0 ? "Edit Product" : "Add Product";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.ProductName)
        @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProductName, "", new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.ProductDescription)
        @Html.TextBoxFor(model => model.ProductDescription, new { @class = "form-control" })
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.ProductPrice)
        @Html.TextBoxFor(model => model.ProductPrice, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProductPrice, "", new { @class = "text-danger" })
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.ProductQuantity)
        @Html.TextBoxFor(model => model.ProductQuantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProductQuantity, "", new { @class = "text-danger" })
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Save</button>
}

PersonalProject/Views/Product/GetAllProducts.cshtml
@model IEnumerable<PersonalProject.BLL.Entities.Product>

@{
    ViewData["Title"] = "Products";
}

<h1>Products</h1>

<p>
    <a asp-action="AddEditProduct" asp-controller="Product">Add New Product</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Product")
            </th>
            <th>
                @Html.DisplayName("Price")
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductPrice)
                </td>
                <td>
                    <a asp-action="AddEditProduct" asp-route-id="@item.Id" asp-controller="Product">Edit</a> |
                    <a asp-action="DeleteProduct" asp-controller="Product" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PersonalProject/Views/Product/Orders.cshtml
@model IEnumerable<PersonalProject.BLL.Models.OrderViewModel>

@{
    ViewData["Title"] = "Orders";
}

<h1>Orders</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCost)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalCost)
                </td>
            </tr>
        }
    </tbody>
</table>

PersonalProject/Views/Product/ProductsToSell.cshtml
@using Newtonsoft.Json;
@using System.Web;
@model PersonalProject.BLL.Models.ShoppingCartModel

@{
    ViewData["Title"] = "Products to sell";
}

<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <section class="main-content">
        @if (Model.ShoppingCartProducts != null && Model.ShoppingCartProducts.Any())
        {
            <div id="shopping-cart">
                @Html.Partial("_ShoppingCart")
            </div>
        }
        <section class="products">
            <table class="table" id="product-table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Product")
                        </th>
                        <th>
                            @Html.DisplayName("Price")
                        </th>
                        <th class="action">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ProductsToSell)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductPrice)
                            </td>
                            <td class="action">
                                <button type="button" class="add-btn" title="Add to shopping cart" data-product-id="@item.ProductId" data-product-name="@item.ProductName" data-product-price="@item.ProductPrice">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </section>
    </section>
</body>

<style>
    .add-btn {
        border-radius: 30px;
        margin-left: 1rem;
    }

    #shopping-cart {
        text-align: -webkit-right;
        width: 100%;
        margin-bottom: 1rem;
    }

    .products {
        width: 90%;
    }

    .action {
        text-align: center;
        width: 15%;
    }

    .main-content {
        display: flex;
        flex-wrap: wrap;
    }
</style>


<script>
    $('.add-btn').click(function () {
        var productId = $(this).data('product-id');
        var productName = $(this).data('product-name');
        var productPrice = $(this).data('product-price');

        var product = {
            productId: productId,
            productName: productName,
            productPrice: productPrice
        };

        addProductToShoppingCart(product);
    });

    function addProductToShoppingCart(product) {
        $.ajax({
            url: '/Product/AddProductsToShoppingCart',
            data: { product: product },
            type: 'POST',
            success: function (response) {
                if (response.success) {
                    toastr.success("Product added successfully", "Success");
                    setTimeout(function () {
                        window.location.reload();
                    }, 700);
                }
            }
        });
    }
</script>

PersonalProject/Views/Product/_ShoppingCart.cshtml
@model PersonalProject.BLL.Models.ShoppingCartModel

<section class="shoppingCart">
    <table class="table" id="shoppingCart-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Product")
                </th>
                <th>
                    @Html.DisplayName("Price")
                </th>
                <th class="action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ShoppingCartProducts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductPrice)
                    </td>
                    <td class="action">
                        <button type="button" title="Delete Product" class="remove-btn" data-product-id="@item.ProductId">
                            <i class="fa fa-trash"></i>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <section class="buttons">
        <div class="purchase">
            <button type="button" title="Purchase" class="purchase-btn">
                <i class="fa fa-credit-card" aria-hidden="true"></i>
            </button>
        </div>
        <div class="pull-right">
            <span>Total Cost: </span> @Html.DisplayFor(model => model.TotalCost)
        </div>
    </section>
</section>
<style>
    .pull-right {
        text-align: end;
        font-weight: 600;
    }

    .shoppingCart {
        width: 25%;
        min-width: 320px;
    }

    .action {
        text-align: center;
        width: 15%;
    }

    .remove-btn {
        border-radius: 30px;
    }

    .buttons {
        display: flex;
        justify-content: space-between;
    }
</style>

<script>
    $(".remove-btn").click(function () {
        let productId = $(this).data('product-id')
        $.ajax({
            url: '/Product/DeleteProductFromShoppingCart',
            data: { productId },
            type: 'POST',
            success: function (response) {
                if (response.success) {
                    toastr.success("Product successfully deleted", "Success");
                    setTimeout(function () {
                        window.location.reload();
                    }, 700);
                }
            }
        });
    })

    $(".purchase-btn").click(function () {
        $.ajax({
            url: '/Product/SaveOrder',
            data: {},
            type: 'POST',
            success: function (response) {
                if (response.success) {
                    toastr.success("Order successfully processed", "Success");
                    setTimeout(function () {
                        window.location.reload();
                    }, 1000);
                }
            }
        });
    })
</script>

PersonalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonalProject.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Include the Toastr CSS file -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    <!-- Include the jQuery library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Include the Toastr JavaScript file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PersonalProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetAllProducts">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="AddEditProduct">Add / Edit Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="DisplayProductsToSell">Products To Sell</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetAllOrders">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PersonalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    .border-top.footer {
        position: absolute;
        bottom: 5%;
        width: 100%;
    }
</style>